### ISSUE TITLE
Fails to compile with gcc-4.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [alasdairmackintosh/google-concurrency-library#5]
```
I failed to make the code compile with gcc-4.4. It fails with:

$ make test
[...]
g++-4.4 test_mutex_test.o condition_variable_test.o lock_test.o race_test.o 
concurrent_priority_queue_test.o blockable_thread.o 
blocking_queue_closed_test.o test_mutex.o gtest-all.o gmock-all.o gmock_main.o 
lower.a stdfake.a -pthread -std=c++0x -o mutex_test.exe
sh ../util/exetest.sh mutex_test
g++-4.4 blocking_queue_test.o source_test.o iterator_queue_test.o 
stream_mutex_test.o buffer_queue_test.o gtest-all.o gmock-all.o gmock_main.o 
lower.a stdfake.a -pthread -std=c++0x -o higher_test.exe
buffer_queue_test.o:(.rodata._ZTCN3gcl12buffer_queueIiEE0_NS_10queue_backIiEE[vt
able for gcl::buffer_queue<int>]+0x60): undefined reference to 
`gcl::queue_back<int>::~queue_back()'
buffer_queue_test.o:(.rodata._ZTCN3gcl12buffer_queueIiEE0_NS_10queue_backIiEE[vt
able for gcl::buffer_queue<int>]+0x68): undefined reference to 
`gcl::queue_back<int>::~queue_back()'
buffer_queue_test.o:(.rodata._ZTCN3gcl12buffer_queueIiEE0_NS_10queue_backIiEE[vt
able for gcl::buffer_queue<int>]+0xe0): undefined reference to `virtual thunk 
to gcl::queue_back<int>::~queue_back()'
buffer_queue_test.o:(.rodata._ZTCN3gcl12buffer_queueIiEE0_NS_10queue_backIiEE[vt
able for gcl::buffer_queue<int>]+0xe8): undefined reference to `virtual thunk 
to gcl::queue_back<int>::~queue_back()'
buffer_queue_test.o:(.rodata._ZTCN3gcl12buffer_queueIiEE208_NS_11queue_frontIiEE
[vtable for gcl::buffer_queue<int>]+0x60): undefined reference to 
`gcl::queue_front<int>::~queue_front()'
buffer_queue_test.o:(.rodata._ZTCN3gcl12buffer_queueIiEE208_NS_11queue_frontIiEE
[vtable for gcl::buffer_queue<int>]+0x68): undefined reference to 
`gcl::queue_front<int>::~queue_front()'
buffer_queue_test.o:(.rodata._ZTCN3gcl10queue_baseIiEE0_NS_10queue_backIiEE[vtab
le for gcl::queue_base<int>]+0x60): undefined reference to 
`gcl::queue_back<int>::~queue_back()'
buffer_queue_test.o:(.rodata._ZTCN3gcl10queue_baseIiEE0_NS_10queue_backIiEE[vtab
le for gcl::queue_base<int>]+0x68): undefined reference to 
`gcl::queue_back<int>::~queue_back()'
buffer_queue_test.o:(.rodata._ZTCN3gcl10queue_baseIiEE0_NS_10queue_backIiEE[vtab
le for gcl::queue_base<int>]+0xe0): undefined reference to `virtual thunk to 
gcl::queue_back<int>::~queue_back()'
buffer_queue_test.o:(.rodata._ZTCN3gcl10queue_baseIiEE0_NS_10queue_backIiEE[vtab
le for gcl::queue_base<int>]+0xe8): undefined reference to `virtual thunk to 
gcl::queue_back<int>::~queue_back()'
buffer_queue_test.o:(.rodata._ZTCN3gcl10queue_baseIiEE8_NS_11queue_frontIiEE[vta
ble for gcl::queue_base<int>]+0x60): undefined reference to 
`gcl::queue_front<int>::~queue_front()'
buffer_queue_test.o:(.rodata._ZTCN3gcl10queue_baseIiEE8_NS_11queue_frontIiEE[vta
ble for gcl::queue_base<int>]+0x68): undefined reference to 
`gcl::queue_front<int>::~queue_front()'
buffer_queue_test.o:(.rodata._ZTVN3gcl12queue_commonIiEE[vtable for 
gcl::queue_common<int>]+0x30): undefined reference to 
`gcl::queue_common<int>::~queue_common()'
buffer_queue_test.o:(.rodata._ZTVN3gcl12queue_commonIiEE[vtable for 
gcl::queue_common<int>]+0x38): undefined reference to 
`gcl::queue_common<int>::~queue_common()'
collect2: ld returned 1 exit status
make[1]: *** [higher_test.exe] Error 1
make[1]: *** Waiting for unfinished jobs....

```

Original issue reported on code.google.com by `mathieu.malaterre` on 24 Jul 2012 at 9:16
