### ISSUE TITLE
Fails to compile with gcc-4.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [alasdairmackintosh/google-concurrency-library#6]
```
I failed to compile the code using gcc-4.7. It fails with:

$ make
[...]
g++ -MMD -MP -Wall -Werror -I. -I../include -g3 -std=c++98 
../testing/counter_test.cc -c -o counter_test.o 
In file included from ../testing/cxx0x_test.cc:15:0:
../include/cxx0x.h:174:1: error: identifier 'nullptr' is a keyword in C++11 
[-Werror=c++0x-compat]
cc1plus: all warnings being treated as errors
make[1]: *** [cxx0x_test.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ./atomic.h:16:0,
                 from ../testing/atomic_cpp_test.cc:15:
../include/cxx0x.h:174:1: error: identifier 'nullptr' is a keyword in C++11 
[-Werror=c++0x-compat]
cc1plus: all warnings being treated as errors
make[1]: *** [atomic_cpp_test.o] Error 1
In file included from ./atomic.h:16:0,
                 from ../include/counter.h:17,
                 from ../testing/counter_test.cc:17:
../include/cxx0x.h:174:1: error: identifier 'nullptr' is a keyword in C++11 
[-Werror=c++0x-compat]
cc1plus: all warnings being treated as errors
make[1]: *** [counter_test.o] Error 1

```

Original issue reported on code.google.com by `mathieu.malaterre` on 24 Jul 2012 at 9:16
